-- ═══════════════════════════════════════════════════════════════════
-- SPCS: Compute pool + stage for Gotenberg service spec
-- Requires: Snowpark Container Services enabled on account
-- Run after: !source deploy_config.sql
-- ═══════════════════════════════════════════════════════════════════

USE ROLE IDENTIFIER($DEPLOY_ROLE);
USE DATABASE IDENTIFIER($DEPLOY_DATABASE);
USE SCHEMA IDENTIFIER($DEPLOY_SCHEMA);
USE WAREHOUSE IDENTIFIER($DEPLOY_WAREHOUSE);

-- Gotenberg bundles Chromium — use at least CPU_X64_M
CREATE COMPUTE POOL IF NOT EXISTS PDF_COMPUTE_POOL
  MIN_NODES = 1
  MAX_NODES = 1
  INSTANCE_FAMILY = CPU_X64_M
  AUTO_RESUME = TRUE
  AUTO_SUSPEND_SECS = 600
  COMMENT = 'Gotenberg PDF converter for EXPORT_PROPOSAL';

CREATE STAGE IF NOT EXISTS SPCS_SPECS
  DIRECTORY = (ENABLE = TRUE)
  COMMENT = 'Snowpark Container Services specification files';

-- Runtime config (PDF endpoint URL filled in after CREATE SERVICE)
CREATE TABLE IF NOT EXISTS PIPELINE_CONFIG (
    CONFIG_KEY   VARCHAR PRIMARY KEY,
    CONFIG_VALUE VARCHAR,
    UPDATED_AT   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

MERGE INTO PIPELINE_CONFIG t
USING (SELECT 'PDF_API_BASE_URL' AS CONFIG_KEY, '' AS CONFIG_VALUE) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE) VALUES (s.CONFIG_KEY, s.CONFIG_VALUE);

MERGE INTO PIPELINE_CONFIG t
USING (SELECT 'PDF_API_ENABLED' AS CONFIG_KEY, 'false' AS CONFIG_VALUE) s
ON t.CONFIG_KEY = s.CONFIG_KEY
WHEN NOT MATCHED THEN INSERT (CONFIG_KEY, CONFIG_VALUE) VALUES (s.CONFIG_KEY, s.CONFIG_VALUE);

SHOW COMPUTE POOLS LIKE 'PDF_COMPUTE_POOL';
