-- ═══════════════════════════════════════════════════════════════════
-- Extend ORCHESTRATOR_STATE for E2E pipeline (idempotent ALTERs)
-- Run after 00_state_tables.sql on existing deployments.
-- ═══════════════════════════════════════════════════════════════════

USE DATABASE IDENTIFIER($DEPLOY_DATABASE);
USE SCHEMA IDENTIFIER($DEPLOY_SCHEMA);

ALTER TABLE IF EXISTS ORCHESTRATOR_STATE ADD COLUMN IF NOT EXISTS CLIENT_NAME VARCHAR;
ALTER TABLE IF EXISTS ORCHESTRATOR_STATE ADD COLUMN IF NOT EXISTS EXPORT_STATUS VARCHAR DEFAULT 'NOT_STARTED'
  COMMENT 'NOT_STARTED | IN_PROGRESS | COMPLETED | FAILED';
ALTER TABLE IF EXISTS ORCHESTRATOR_STATE ADD COLUMN IF NOT EXISTS SEARCH_INDEXED BOOLEAN DEFAULT FALSE;
ALTER TABLE IF EXISTS ORCHESTRATOR_STATE ADD COLUMN IF NOT EXISTS FINAL_STAGE_PATH VARCHAR
  COMMENT 'Stage path prefix @CLIENT_DOCS/{client}/final/';

ALTER TABLE IF EXISTS STAGE_OUTPUTS ADD COLUMN IF NOT EXISTS STAGE_FILE_PATH VARCHAR
  COMMENT 'Path written to @CLIENT_DOCS/{client}/working/{run_id}/';
