-- ═══════════════════════════════════════════════════════════════════
-- Ingest + E2E pipeline permissions
-- Run after all ingest SPs, stages, and search services are created.
-- ═══════════════════════════════════════════════════════════════════

USE ROLE SECURITYADMIN;

-- Stage and registry tables
GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.CLIENTS TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.CLIENT_FILES TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.SOURCE_DOCUMENTS TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.SOURCE_DOCUMENT_CHUNKS TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.WORKFLOW_OUTPUTS TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.PROPOSAL_DECK TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.SKILLS TO ROLE "SPS-SF-SYNC";

-- Internal stage
GRANT READ, WRITE ON STAGE SPS_BUSINESS_INSIGHT.NEXUS.CLIENT_DOCS TO ROLE "SPS-SF-SYNC";

-- Ingest / export stored procedures
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.SYNC_CLIENT_ASSETS(VARCHAR) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.SYNC_ALL_ACTIVE_CLIENTS() TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.INGEST_CLIENT_ASSETS(VARCHAR, VARCHAR) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.INDEX_HARNESS_CHUNKS(VARCHAR, VARCHAR, VARCHAR, NUMBER) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.SYNC_SKILLS_FROM_GIT() TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.EXPORT_PROPOSAL(VARCHAR) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.INDEX_FINAL_ASSETS(VARCHAR) TO ROLE "SPS-SF-SYNC";

-- Updated init signature (3-arg)
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.INIT_WORKFLOW(VARCHAR, VARCHAR, VARCHAR) TO ROLE "SPS-SF-SYNC";

-- Cortex Search services
GRANT USAGE ON CORTEX SEARCH SERVICE SPS_BUSINESS_INSIGHT.NEXUS.SOURCE_DOCUMENTS_SEARCH TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON CORTEX SEARCH SERVICE SPS_BUSINESS_INSIGHT.NEXUS.PROPOSAL_DECK_SEARCH TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON CORTEX SEARCH SERVICE SPS_BUSINESS_INSIGHT.NEXUS.SKILLS_SEARCH_SERVICE TO ROLE "SPS-SF-SYNC";

-- Deck research agent
GRANT USAGE ON AGENT SPS_BUSINESS_INSIGHT.NEXUS.DECK_RESEARCH_AGENT TO ROLE "SPS-SF-SYNC";

-- SPCS (Gotenberg PDF service)
GRANT USAGE ON COMPUTE POOL SPS_BUSINESS_INSIGHT.NEXUS.PDF_COMPUTE_POOL TO ROLE "SPS-SF-SYNC";
GRANT MONITOR ON SERVICE SPS_BUSINESS_INSIGHT.NEXUS.GOTENBERG_PDF_SERVICE TO ROLE "SPS-SF-SYNC";
GRANT SELECT ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.PIPELINE_CONFIG TO ROLE "SPS-SF-SYNC";

-- Scheduled tasks (run as role owner)
GRANT EXECUTE TASK ON ACCOUNT TO ROLE "SPS-SF-SYNC";
GRANT OPERATE ON TASK SPS_BUSINESS_INSIGHT.NEXUS.TASK_SYNC_CLIENT_ASSETS TO ROLE "SPS-SF-SYNC";
GRANT OPERATE ON TASK SPS_BUSINESS_INSIGHT.NEXUS.TASK_SYNC_SKILLS_FROM_GIT TO ROLE "SPS-SF-SYNC";

-- External Access (uncomment after EAI created by ACCOUNTADMIN)
-- GRANT USAGE ON INTEGRATION GOOGLE_DRIVE_EAI TO ROLE "SPS-SF-SYNC";
-- GRANT USAGE ON INTEGRATION PDF_API_EAI TO ROLE "SPS-SF-SYNC";
-- GRANT READ ON SECRET GOOGLE_DRIVE_SERVICE_ACCOUNT TO ROLE "SPS-SF-SYNC";
