-- ============================================================
-- ORCHESTRATION STATE TABLES
-- Schema: SPS_BUSINESS_INSIGHT.NEXUS
-- Purpose: State management for multi-agent workflow orchestration
-- ============================================================

USE ROLE SYSADMIN;
USE DATABASE SPS_BUSINESS_INSIGHT;
USE SCHEMA NEXUS;

-- ============================================================
-- TABLE 1: ORCHESTRATOR_STATE
-- One row per workflow run. Tracks current stage and stores
-- the brief (SSOT) for the entire run.
-- ============================================================

CREATE TABLE IF NOT EXISTS SPS_BUSINESS_INSIGHT.NEXUS.ORCHESTRATOR_STATE (
    RUN_ID              VARCHAR DEFAULT UUID_STRING()    COMMENT 'Unique workflow run identifier',
    PROJECT_NAME        VARCHAR                          COMMENT 'Human-readable project name',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CURRENT_STAGE       NUMBER DEFAULT 1                 COMMENT 'Current workflow stage (1-8)',
    STAGE_STATUS        VARCHAR DEFAULT 'NOT_STARTED'    COMMENT 'NOT_STARTED | IN_PROGRESS | AWAITING_REVIEW | COMPLETED | FAILED',
    BRIEF_CONTENT       VARCHAR                          COMMENT 'The SSOT brief generated by Stage 1',
    USER_RFP_INPUT      VARCHAR                          COMMENT 'Original RFP/notes provided by user',
    REVIEW_GATE_PENDING BOOLEAN DEFAULT FALSE            COMMENT 'TRUE when waiting for user approval at a review gate',
    RETRY_COUNT         NUMBER DEFAULT 0                 COMMENT 'Number of evaluation retries for current agent',
    MAX_RETRIES         NUMBER DEFAULT 2                 COMMENT 'Maximum retries before escalating to user',
    METADATA            VARIANT                          COMMENT 'Extensible JSON metadata',
    CLIENT_NAME         VARCHAR                          COMMENT 'Client slug for @CLIENT_DOCS/{client}/ paths',
    EXPORT_STATUS       VARCHAR DEFAULT 'NOT_STARTED'    COMMENT 'NOT_STARTED | IN_PROGRESS | COMPLETED | COMPLETED_MD_ONLY | FAILED',
    SEARCH_INDEXED      BOOLEAN DEFAULT FALSE            COMMENT 'TRUE after INDEX_FINAL_ASSETS completes',
    FINAL_STAGE_PATH    VARCHAR                          COMMENT '@CLIENT_DOCS/{client}/final/ after export'
);

-- ============================================================
-- TABLE 2: STAGE_OUTPUTS
-- One row per agent output. Stores the full output and its
-- evaluation status. Enables cross-consistency checks.
-- ============================================================

CREATE TABLE IF NOT EXISTS SPS_BUSINESS_INSIGHT.NEXUS.STAGE_OUTPUTS (
    OUTPUT_ID           VARCHAR DEFAULT UUID_STRING()    COMMENT 'Unique output identifier',
    RUN_ID              VARCHAR                          COMMENT 'FK to ORCHESTRATOR_STATE.RUN_ID',
    STAGE_NUMBER        NUMBER                           COMMENT 'Workflow stage that produced this output',
    AGENT_NAME          VARCHAR                          COMMENT 'Agent that generated this output (e.g. RFP_ANALYZER_AGENT)',
    SKILL_NAME          VARCHAR                          COMMENT 'Source skill name (e.g. sales-rfp-analyzer)',
    OUTPUT_CONTENT      VARCHAR                          COMMENT 'Full markdown output from the agent',
    EVALUATION_STATUS   VARCHAR DEFAULT 'PENDING'        COMMENT 'PENDING | PASS | FAIL',
    EVALUATION_FEEDBACK VARCHAR                          COMMENT 'Feedback from evaluator (populated on FAIL)',
    EXECUTION_ORDER     NUMBER                           COMMENT 'Order of execution within the stage',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STAGE_FILE_PATH     VARCHAR                          COMMENT 'Path on @CLIENT_DOCS/{client}/working/{run_id}/'
);

-- ============================================================
-- TABLE 3: EVALUATION_LOG
-- Audit trail of every evaluation performed by the Evaluator
-- Agent. Supports debugging and quality trend analysis.
-- ============================================================

CREATE TABLE IF NOT EXISTS SPS_BUSINESS_INSIGHT.NEXUS.EVALUATION_LOG (
    EVAL_ID             VARCHAR DEFAULT UUID_STRING()    COMMENT 'Unique evaluation identifier',
    RUN_ID              VARCHAR                          COMMENT 'FK to ORCHESTRATOR_STATE.RUN_ID',
    STAGE_NUMBER        NUMBER                           COMMENT 'Stage being evaluated',
    AGENT_NAME          VARCHAR                          COMMENT 'Agent whose output is being evaluated',
    ALIGNMENT_SCORE     NUMBER(5,2)                      COMMENT 'Quality score 0-100',
    VERDICT             VARCHAR                          COMMENT 'PASS or FAIL',
    BREAKDOWN           VARIANT                          COMMENT 'JSON breakdown by category',
    ISSUES_FOUND        VARIANT                          COMMENT 'JSON array of identified issues',
    FEEDBACK            VARCHAR                          COMMENT 'Actionable feedback sent to agent on retry',
    ATTEMPT_NUMBER      NUMBER                           COMMENT 'Which attempt this evaluation covers (1-based)',
    CREATED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

-- ============================================================
-- INDEXES / CLUSTERING (optional, for performance at scale)
-- ============================================================

-- ALTER TABLE SPS_BUSINESS_INSIGHT.NEXUS.STAGE_OUTPUTS
--   CLUSTER BY (RUN_ID, STAGE_NUMBER);

-- ALTER TABLE SPS_BUSINESS_INSIGHT.NEXUS.EVALUATION_LOG
--   CLUSTER BY (RUN_ID, STAGE_NUMBER);
