-- ============================================================
-- ORCHESTRATION PERMISSIONS
-- Schema: SPS_BUSINESS_INSIGHT.NEXUS
-- Purpose: Grant access to all orchestration objects
-- ============================================================
-- Run AFTER all tables, procedures, and agents are created.
--
-- Objects:
--   4 Cortex Agents: ORCHESTRATOR_AGENT, PLANNER_AGENT, WORKER_AGENT, EVALUATOR_AGENT
--   7 Stored Procedures: INIT_WORKFLOW, GET_WORKFLOW_STATE, EXECUTE_SKILL_TASK, RUN_SKILL,
--                        PLAN_STAGE, EVALUATE_OUTPUT, ADVANCE_STAGE
--   3 Tables: ORCHESTRATOR_STATE, STAGE_OUTPUTS, EVALUATION_LOG
-- ============================================================

USE ROLE SECURITYADMIN;

-- ============================================================
-- SECTION 1: WAREHOUSE & DATABASE ACCESS
-- ============================================================

GRANT USAGE ON WAREHOUSE SPS_MAIN_WH_XS TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON DATABASE SPS_BUSINESS_INSIGHT TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON SCHEMA SPS_BUSINESS_INSIGHT.NEXUS TO ROLE "SPS-SF-SYNC";

-- ============================================================
-- SECTION 2: STATE TABLES
-- ============================================================

GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.ORCHESTRATOR_STATE TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.STAGE_OUTPUTS TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.EVALUATION_LOG TO ROLE "SPS-SF-SYNC";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.SOURCE_DOCUMENT_CHUNKS TO ROLE "SPS-SF-SYNC";

GRANT USAGE ON CORTEX SEARCH SERVICE SPS_BUSINESS_INSIGHT.NEXUS.SOURCE_DOCUMENTS_SEARCH TO ROLE "SPS-SF-SYNC";

-- ============================================================
-- SECTION 3: SKILLS TABLE (existing, needed by RUN_SKILL)
-- ============================================================

GRANT SELECT ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.SKILLS TO ROLE "SPS-SF-SYNC";

-- ============================================================
-- SECTION 4: STORED PROCEDURES
-- ============================================================

-- Workflow management
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.INIT_WORKFLOW(VARCHAR, VARCHAR, VARCHAR) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.GET_WORKFLOW_STATE(VARCHAR) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.ADVANCE_STAGE(VARCHAR, BOOLEAN) TO ROLE "SPS-SF-SYNC";

-- Worker (skill execution)
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.EXECUTE_SKILL_TASK(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.RUN_SKILL(VARCHAR, VARCHAR, VARCHAR, VARCHAR) TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.INDEX_HARNESS_CHUNKS(VARCHAR, VARCHAR, VARCHAR, NUMBER) TO ROLE "SPS-SF-SYNC";

-- Planner (calls PLANNER_AGENT)
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.PLAN_STAGE(VARCHAR, NUMBER) TO ROLE "SPS-SF-SYNC";

-- Evaluator (calls EVALUATOR_AGENT)
GRANT USAGE ON PROCEDURE SPS_BUSINESS_INSIGHT.NEXUS.EVALUATE_OUTPUT(VARCHAR, VARCHAR, NUMBER) TO ROLE "SPS-SF-SYNC";

-- ============================================================
-- SECTION 5: CORTEX AGENTS
-- ============================================================

-- User-facing orchestrator
GRANT USAGE ON AGENT SPS_BUSINESS_INSIGHT.NEXUS.ORCHESTRATOR_AGENT TO ROLE "SPS-SF-SYNC";

-- Sub-agents (called internally by stored procedures)
GRANT USAGE ON AGENT SPS_BUSINESS_INSIGHT.NEXUS.PLANNER_AGENT TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON AGENT SPS_BUSINESS_INSIGHT.NEXUS.WORKER_AGENT TO ROLE "SPS-SF-SYNC";
GRANT USAGE ON AGENT SPS_BUSINESS_INSIGHT.NEXUS.EVALUATOR_AGENT TO ROLE "SPS-SF-SYNC";

-- Future agents in schema
GRANT USAGE ON FUTURE AGENTS IN SCHEMA SPS_BUSINESS_INSIGHT.NEXUS TO ROLE "SPS-SF-SYNC";

-- ============================================================
-- OPTIONAL: Grant to end-user roles (e.g., business development)
-- ============================================================
-- GRANT USAGE ON AGENT SPS_BUSINESS_INSIGHT.NEXUS.ORCHESTRATOR_AGENT TO ROLE "SPS-SF-BD";
-- GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.ORCHESTRATOR_STATE TO ROLE "SPS-SF-BD";
-- GRANT SELECT, INSERT, UPDATE ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.STAGE_OUTPUTS TO ROLE "SPS-SF-BD";
-- GRANT SELECT, INSERT ON TABLE SPS_BUSINESS_INSIGHT.NEXUS.EVALUATION_LOG TO ROLE "SPS-SF-BD";
-- (repeat procedure grants for the role)
